filter:
    excluded_paths: [ "vendor/*", "dev/*" ]

tools:
    # https://scrutinizer-ci.com/docs/tools/external-code-coverage/
    external_code_coverage:
        runs: 4    # Wait for four code coverage submissions

    # https://scrutinizer-ci.com/docs/tools/php/php-analyzer/
    php_analyzer: true

    # https://scrutinizer-ci.com/docs/tools/php/change-tracking-analyzer/
    php_changetracking: false

    # https://scrutinizer-ci.com/docs/tools/php/code-sniffer/
    php_code_sniffer:
        config:
            standard: "PSR1"
        filter:
            excluded_paths: [ "vendor/*", "dev/*" ]

    # https://scrutinizer-ci.com/docs/tools/php/mess-detector/
    php_mess_detector: false

    # https://scrutinizer-ci.com/docs/tools/php/pdepend/
    php_pdepend: true

    # https://scrutinizer-ci.com/docs/tools/php/code-similarity-analyzer/
    php_sim: true

    # https://scrutinizer-ci.com/docs/tools/php/security-advisory-checker/
    sensiolabs_security_checker: true
