language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer install
  - touch /tmp/oodb.db

script:
  - vendor/bin/phpunit --configuration dev/phpunit.xml --colors --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
